version: "3.9"

networks:
  lan_etudiant:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24

  lan_serveurs:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24

  wan_sim:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24

services:

  routeur:
    image: nicolaka/netshoot
    container_name: routeur
    cap_add: [NET_ADMIN]
    sysctls:
      net.ipv4.ip_forward: 1
    networks:
      lan_etudiant:
        ipv4_address: 10.10.1.254
      lan_serveurs:
        ipv4_address: 10.10.2.254
      wan_sim:
        ipv4_address: 10.10.3.254
    command: >
      sh -c "
        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;
        tail -f /dev/null
      "

  switch_lan:
    image: nicolaka/netshoot
    container_name: switch_lan
    cap_add: [NET_ADMIN]
    networks:
      lan_etudiant:
        ipv4_address: 10.10.1.2
    command: tail -f /dev/null

  pc_a:
    image: nicolaka/netshoot
    container_name: pc_a
    cap_add: [NET_ADMIN]
    networks:
      lan_etudiant:
        ipv4_address: 10.10.1.10
    command: tail -f /dev/null

  pc_b:
    image: nicolaka/netshoot
    container_name: pc_b
    cap_add: [NET_ADMIN]
    networks:
      lan_etudiant:
        ipv4_address: 10.10.1.11
    command: tail -f /dev/null

  srv_web:
    image: httpd:2.4
    container_name: srv_web
    networks:
      lan_serveurs:
        ipv4_address: 10.10.2.10
    volumes:
      - ./www:/usr/local/apache2/htdocs/

  srv_dns:
    image: andyshinn/dnsmasq
    container_name: srv_dns
    cap_add: [NET_ADMIN]
    networks:
      lan_serveurs:
        ipv4_address: 10.10.2.53
    command: >
      --no-daemon
      --address=/srv-web.local/10.10.2.10
      --address=/srv-dns.local/10.10.2.53
      --address=/routeur.local/10.10.2.254
      --log-queries
      --log-facility=-

  log_generator:
    image: python:3.11-slim
    container_name: log_generator
    volumes:
      - ./logs:/logs
      - ./scripts:/scripts
    networks:
      lan_etudiant:
        ipv4_address: 10.10.1.99
    command: sh -c "pip install -q --break-system-packages 2>/dev/null; python /scripts/generate_logs.py"

